model_family: qwen3_5_2b

data_path: ./dataset/full_merged_all_10_lang
batch_size: 1
gradient_accumulation_steps: 8
num_epochs: 5
lr: 2e-5
save_dir: ../scratch/tofu_finetuned_5epoch_qwen3_5_2b_base_2e5/

weight_decay: 0.01
seed: 42
