aya-expanse-8B:
  hf_key: "CohereForAI/aya-expanse-8b"
  question_start_tag:
    en: "Question: "
    fr: "Question: "
    ar: "السؤال: "
    fa: "سوال: "
    hi: "प्रश्न: "
    iw: "שאלה: "          # Hebrew
    id: "Pertanyaan: "    # Indonesian
    ja: "質問: "          # Japanese
    ko: "질문: "          # Korean
    ru: "Вопрос: "        # Russian
  question_end_tag: " \n"
  answer_tag:
    en: "Answer: "
    fr: "Reponse: "
    ar: "الإجابة: "
    fa: "پاسخ: "
    hi: "उत्तर: "
    iw: "תשובה: "        # Hebrew
    id: "Jawaban: "       # Indonesian
    ja: "回答: "          # Japanese
    ko: "답변: "          # Korean
    ru: "Ответ: "         # Russian
  flash_attention2: "true"
  gradient_checkpointing: "false"
  ft_model_path: "maral/tofu_ft_aya"
  use_chat_template: "false"

qwen3_5_2b:
  hf_key: "Qwen/Qwen3.5-2B-Base"
  question_start_tag:
    en: "Question: "
    fr: "Question: "
    ar: "السؤال: "
    fa: "سوال: "
    hi: "प्रश्न: "
    iw: "שאלה: "          # Hebrew
    id: "Pertanyaan: "    # Indonesian
    ja: "質問: "          # Japanese
    ko: "질문: "          # Korean
    ru: "Вопрос: "        # Russian
  question_end_tag: " \n"
  answer_tag:
    en: "Answer: "
    fr: "Reponse: "
    ar: "الإجابة: "
    fa: "پاسخ: "
    hi: "उत्तर: "
    iw: "תשובה: "        # Hebrew
    id: "Jawaban: "       # Indonesian
    ja: "回答: "          # Japanese
    ko: "답변: "          # Korean
    ru: "Ответ: "         # Russian
  flash_attention2: "false"
  gradient_checkpointing: "true"
  ft_model_path: "../scratch/tofu_ft_qwen3_5_2b"
  use_chat_template: "true"

qwen3.5-2B:
  hf_key: "Qwen/Qwen3.5-2B"
  question_start_tag:
    en: "Question: "
    fr: "Question: "
    ar: "السؤال: "
    fa: "سوال: "
    hi: "प्रश्न: "
    iw: "שאלה: "
    id: "Pertanyaan: "
    ja: "質問: "
    ko: "질문: "
    ru: "Вопрос: "
    zh: "问题: "
  question_end_tag: " \n"
  answer_tag:
    en: "Answer: "
    fr: "Reponse: "
    ar: "الإجابة: "
    fa: "پاسخ: "
    hi: "उत्तर: "
    iw: "תשובה: "
    id: "Jawaban: "
    ja: "回答: "
    ko: "답변: "
    ru: "Ответ: "
    zh: "回答: "
  flash_attention2: "false"
  gradient_checkpointing: "true"
  ft_model_path: "Qwen/Qwen3.5-2B"
  use_chat_template: "true"
